# Generated by Django 5.2.4 on 2025-08-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='catogories_movies', to='movies.catogory'),
        ),
    ]
