# Generated by Django 5.2.4 on 2025-08-06 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
        ('movies', '0002_remove_movies_genre_movies_director_movies_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(default='Unknown', max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='catogories_movies', to='movies.catogory')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviess_reviews', to='movies.movie'),
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('brack_time', models.TimeField(default='00:15', verbose_name='brack time by minutes')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='halls.hall')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.movie')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
