# Generated by Django 5.2.4 on 2025-08-06 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
        ('movies', '0003_movie_alter_review_movies_screening_delete_movies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_tickets', to='movies.screening')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_tickets', to='halls.seats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('screening', 'seat')},
            },
        ),
    ]
